### PR TITLE
add ocamlformat github action

### PR DESCRIPTION
**Pull request by hannesm**
expectation for this PR is to fail (since the code isn't ocamlformat-formatted).

//cc @PizieDust

### CODE REVIEW

**Comment by hannesm** [comment]
So, this is my proposal. A GitHub action that potentially adds a commit with the autoformatted code. What do you think?

**Comment by PizieDust** [comment]
> So, this is my proposal. A GitHub action that potentially adds a commit with the autoformatted code. What do you think?

This will be amazing. Is the pipeline costly to run? If so, we can always just try to remember to run `ocamlformat` before pushing, else this is a really awesome idea to have the CI format and add a commit.

**Comment by hannesm** [comment]
It took 3 minutes. I think if you've your editor with ocamlformat, that's fine. But if not, don't worry, and the CI will take care of it.

**Comment by PizieDust** [comment]
> It took 3 minutes. I think if you've your editor with ocamlformat, that's fine. But if not, don't worry, and the CI will take care of it.

Okay great. I do have ocamlformat. I guess I just have to run `ocamlformat --inplace` before pushing

**Pull request merged**
