### PR TITLE
Landing page

### PR DESCRIPTION
**Pull request by PizieDust**
Make the landing page a little more organized and some minor fixes.

### CODE REVIEW

**Comment by hannesm** [comment]
this looks fine to me, the only question I have whether we can scale down the images (> 1MB and 500kB is quite a lot). WDYT?

**Comment by hannesm** [comment]
I downsized the images. thanks a lot.

**Comment by reynir** [comment]
In assets/albatross_1.png albatross is misspelt twice in different ways, and in assets/mirage_os_1.png mirage is also misspelt just FYI.

**Comment by hannesm** [comment]
thanks @reynir -- @PizieDust any chance you can modify the original images to fix the typos? I used (from ImageMagick) `convert <file> -resize <current-pixels / 5> <file>.2`, followed by `mv <file>.2 <file>` for downscaling -- now the pixels are ~200x200, which looks sufficient.

**Comment by hannesm** [comment]
I squash-merged so that git doesn't retain the big files in the repository.

**Comment by PizieDust** [comment]
@reynir thanks for the catch. I can correct the typos

**Pull request merged**
